### ISSUE TITLE
Displaying Items on Vendor's Profile

### ISSUE THREAD

**Issue by derrickhnguyen** [Murgaloids/murgaloids#3]
As a user, I want to be able to see other vendor's profile and the items that they are selling because I want to know who I am doing business and the type of stuff that they are selling.

**Comment by cebh** [comment]
Hasn't this already been implemented using .../items/all?userId=#. Seem that the frontend is already using it and it works as intended.

**Comment by derrickhnguyen** [comment]
You're right, we can close this
