### ISSUE TITLE
Add timestamp for items

### ISSUE THREAD

**Issue by derrickhnguyen** [Murgaloids/murgaloids#38]
As a user, I want to be able to search for the most recent items available because I like new stuff.

**Comment by cebh** [comment]
@derrickhnguyen I'm getting errors building once I tried adding the timestamp to the Item.java and to local mysql. Have you encountered this before?

**Comment by derrickhnguyen** [comment]
@cebh on the `master` repo?

**Comment by cebh** [comment]
no, on my branch. I altered the table on my local mysql database to include the timestamp.

**Comment by derrickhnguyen** [comment]
@cebh Okay, I'm working on it right now

**Comment by cebh** [comment]
I think it's a problem with my database. I tried adding timestamp then removed it and it's not building. Going to reset my database.

**Comment by derrickhnguyen** [comment]
@cebh refer to https://github.com/Murgaloids/murgaloids/pull/47

Clone my branch and test it out yourself and see if there's any errors. Also, test if timestamp is being autogenerated when you add a new item to sql

**Comment by cebh** [comment]
I cloned master to my branch. Date added seems to be working in the database, but not in the Item object itself. GET requests don't return the date added.

**Comment by derrickhnguyen** [comment]
@cebh fixing the problem right now

**Comment by derrickhnguyen** [comment]
@cebh I ammended my change on the branch. Re-clone the repository and test it out again, including the get method and the delete method.

**Comment by cebh** [comment]
Get and delete work, and the timestamp seems to be displaying correctly. Should I accept the current pull request or are you going to make a new one?

**Comment by derrickhnguyen** [comment]
@cebh the pull request automatically updates the changes i make from my branch, it should be good to go.
