### ISSUE TITLE
Cannot add two items with the same name to database.

### ISSUE THREAD

**Issue by cebh** [Murgaloids/murgaloids#46]
As a developer, I want to be able to add two items with the same name to the database because students may have items with generic names, and the only unique identifier should be the id.

**Comment by derrickhnguyen** [comment]
@cebh, I editted the sql table to remove the secondary key of sellerId and itemName. Reset your sql in your local development server and check it out

**Comment by cebh** [comment]
How do I reset the sql in local development server?
